name: Trigger API every 10 min
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: curl https://stacks-whale-alert.vercel.app/api/check-transfers
